products = ['iPhone', 'iPad', 'MacBook','Mac Book', 'Apple Watch', 'iMac', 'AirPods', 'HomePod', 'Apple TV', 'iPhone',
    'iPhone 3G',
    'iPhone 3GS',
    'iPhone 4',
    'iPhone 4s',
    'iPhone 5',
    'iPhone 5s' ,'iPhone 5c',
    'iPhone 6',  'iPhone 6 Plus',
    'iPhone 6s ','iPhone 6s Plus',
    'iPhone SE',
    'iPhone 7 ','iPhone 7 Plus',
    'iPhone 8 ','iPhone 8 Plus',
    'iPhone X',
    'iPhone XR','iPhone XS','iPhone XS Max',
    'iPhone 11','iPhone 11 Pro' ,'iPhone 11 Pro Max',
    'iPhone SE (2nd generation)',
    'iPhone 12','iPhone 12 mini','iPhone 12 Pro','iPhone 12 Pro Max',
    'iPhone 13','iPhone 13 mini','iPhone 13 Pro','iPhone 13 Pro Max',
    'iPhone SE (3rd generation)',
    'iPhone 14','iPhone 14 Plus','iPhone 14 Pro','iPhone 14 Pro Max',
    'iPhone 15','iPhone 15 Plus','iPhone 15 Pro','iPhone 15 Pro Max',
     'Air purifier',
    'Air conditioner',
    'Alarm clock',
    'Backup charger',
    'Bread maker',
    'Banknote counter',
    'Blender',
    'Bluetooth speaker',
    'Bulb',
    'Calculator',
    'Car toy',
    'Ceiling fan',
    'Chandelier',
    'Clock',
    'Clothes dryer',
    'Coffee maker',
    'Computer',
    'Copier',
    'Curling iron',
    'Digital camera',
    'camera',
    'samsung camera',
    'Dishwasher',
    'Doorbell camera',
    'Drill',
    'TV',
    'Television',
    'Dvd player',
    'Earphones',
    'Electric frying pan',
    'Electric grill',
    'Electric guitar',
    'Electric pencil sharpener',
    'Electric razor',
    'Electric stove',
    'Exhaust fan',
    'External hard drive',
    'Fan',
    'Facial cleansing machine',
    'Fax',
    'Fish tank',
    'Floor lamp',
    'Game controller',
    'Grandfather clock',
    'Hair dryer',
    'Headset',
    'Inkjet printer',
    'iPod',
    'Iron',
    'Juicer',
    'Kettle',
    'Kitchen scale',
    'Hair straightening machine',
    'Laser printer',
    'Lawn mower',
    'Lift',
    'Meat grinder',
    'Microphone',
    'Microwave',
    'Mixer',
    'Monitor',
    'Mosquito racket',
    'Mouse',
    'Mp3 player',
    'Oil-free fryer',
    'Piano',
    'Oven',
    'Plotter',
    'Pressure cooker',
    'Printer',
    'Projector',
    'Radiator',
    'Radio',
    'Reading lamp',
    'Refrigerator',
    'Remote control',
    'Rice cooker',
    'Safe',
    'Robotic vacuum cleaner',
    'Sandwich maker',
    'Scale',
    'Scanner',
    'Sewing machine',
    'Smart television',
    'Smartphone',
    'Speakers',
    'Tablet',
    'Television',
    'Timer',
    'Toaster',
    'Torch',
    'USB drive',
    'Vacuum cleaner',
    'Walkie-talkie',
    'Washing machine',
    'Watch',
    'Water pumps',
    'Water purifier',
    'Wall fan',
    'Water heater',
    'Webcam',
    'Wifi modem',
    'Wi fi',
    'Wifi',
    'Skirt',
    'Bikini',
    'Dress pants',
    'Jumper',
    'Sneakers',
    'Hoodie',
    'Vest',
    'High heels',
    'Flip flops',
    'Handbag',
    'Tank top',
    'Singlet',
    'Boots',
    'Shorts',
    'Polo shirt',
    'Umbrella',
    'Dress',
    'Hawaiian shirt',
    'Mittens',
    'Socks',
    'Swimsuit',
    'Trench coat',
    'Winter coat',
    'Straw hat',
    'Cap',
    'Scarf',
    'Sunglasses',
    'Apron',
    'Necklace',
    'Watch',
    'Tie',
    'Bow tie',
    'Purse',
    'Ring',
    'Gloves',
    'Hair clip (U.K) – Bobby pin (U.S)',
    'Hair band',
    'Safety pin',
    'Overalls',
    'Beanie',
    'Baby apron',
    'Diaper',
    'Shoes',
    'Sweater',
    'Shirt',
    'Jeans',
    'Suit',
    'Business shoes',
    'Cardigan',
    'Jacket',
    'Sport shoes',
    'Sleeveless shirt',
    'Long-sleeve top',
    'Bathrobe',
    'Cargo pants',
    'Blazer',
    'T-shirt',
    'Belt',
    'Underpants',
    'Waistcoat',
    'Pullover',
    'Glasses',
    'Wallet',
    'Apple MacBook Pro',
    'Dell XPS 13',
    'HP Spectre x360',
    'Lenovo ThinkPad X1 Carbon',
    'Microsoft Surface Laptop',
    'Asus ROG Zephyrus G14',
    'Acer Swift 3',
    'Razer Blade 15',
    'Lenovo Yoga C940',
    'HP Envy 13',
    'Dell Inspiron 15',
    'Lenovo Legion Y740',
    'Microsoft Surface Book',
    'Asus ZenBook Pro Duo',
    'Acer Predator Helios 300',
    'HP Pavilion 15',
    'Dell Latitude 7490',
    'Lenovo IdeaPad 330S',
    'Apple MacBook Air',
    'Asus VivoBook S15',
    'MSI GS66 Stealth',
    'Acer Aspire 5',
    'HP Omen 15',
    'Lenovo ThinkPad X1 Extreme',
    'Dell G5 15',
    'Microsoft Surface Pro',
    'Asus ROG Strix Scar III',
    'Acer Chromebook 14',
    'HP EliteBook x360',
    'Lenovo ThinkPad T490',
    'MSI Prestige 14',
    'Asus TUF Gaming A15',
    'Dell Precision 7550',
    'Apple MacBook',
    'Acer Swift 5',
    'HP ProBook 450',
    'Lenovo Legion 5',
    'Microsoft Surface Go',
    'Asus ZenBook 14',
    'Razer Blade Stealth',
    'Dell XPS 15',
    'Lenovo Yoga C740',
    'HP ZBook Studio',
    'Acer Nitro 5',
    'MSI Creator 15',
    'Asus ROG Zephyrus S',
    'Dell Alienware Area-51m',
    'Lenovo ThinkPad X13',
    'Apple MacBook Pro M1',
    'HP Spectre x360 13',
    'Asus ROG Zephyrus G15',
    'Labtop',
    'dell laptop',
    'Lenovo labtop',
    'apple laptop',
    'MSi labtop',
    'samsung labtop',
    'samsung tv',
    'toshiba labtop',
    'Samsung Galaxy S21',
    'Google Pixel 6',
    'OnePlus 9 Pro',
    'Xiaomi Mi 11',
    'Sony Xperia 1 III',
    'Huawei P40 Pro',
    'LG Velvet',
    'Motorola Edge+',
    'Nokia 9 PureView',
    'Samsung Galaxy Note 20 Ultra',
    'Google Pixel 5a',
    'OnePlus 8T',
    'Xiaomi Redmi Note 10 Pro',
    'Sony Xperia 5 III',
    'Huawei Mate 40 Pro',
    'LG Wing',
    'Motorola Moto G Power',
    'Nokia 8.3 5G',
    'Samsung Galaxy S20 FE',
    'Google Pixel 4a',
    'OnePlus Nord',
    'Xiaomi Poco X3 Pro',
    'Sony Xperia 10 III',
    'Huawei P30 Pro',
    'LG G8 ThinQ',
    'Motorola Moto G Stylus',
    'Nokia 7.2',
    'Samsung Galaxy A52',
    'Google Pixel 4a 5G',
    'OnePlus 9',
    'Xiaomi Mi 10T Pro',
    'Sony Xperia 5 II',
    'Huawei Mate X2',
    'LG V60 ThinQ',
    'Motorola Moto G Play',
    'Nokia 6.2',
    'Samsung Galaxy A72',
    'Google Pixel 4',
    'OnePlus 9R',
    'Xiaomi Redmi Note 9 Pro',
    'Sony Xperia 10 II',
    'Huawei Mate 30 Pro',
    'LG Velvet 5G',
    'Motorola Moto E7',
    'Nokia 5.4',
    'Samsung Galaxy A51',
    'Google Pixel 3a',
    'OnePlus Nord CE 5G',
    'Xiaomi Mi 11 Lite',
    'Sony Xperia 1 II',
    'Huawei P20 Pro',
    'LG K92 5G',
    'Motorola Moto G Fast',
    'Nokia 3.4',
    'Samsung Galaxy A31',
    'Google Pixel 3',
    'OnePlus 8',
    'Xiaomi Redmi Note 8 Pro',
    'Sony Xperia 5',
    'Huawei Mate 20 Pro',
    'LG K51',
    'Motorola Moto G Power (2021)',
    'Nokia 2.4',
    'Samsung Galaxy A21s',
    'Google Pixel 3 XL',
    'OnePlus 8 Pro',
    'Xiaomi Mi 10T Lite',
    'Sony Xperia 10',
    'Huawei P10 Plus',
    'LG K61',
    'Motorola Moto G9 Play',
    'Nokia 1.4',
    'Samsung Galaxy A11',
    'Google Pixel 2',
    'OnePlus 7T',
    'Xiaomi Redmi Note 7',
    'Sony Xperia XZ3',
    'Huawei Nova 7i',
    'LG K51S',
    'Motorola Moto E6',
    'Nokia 2.3'
    ]